# Site
name: "31 de Junho"
title: "31 de Junho"
description: "Um Mundo ..."
logo: ''
favicon: 'assets/images/logohead.png'
url: "https://blogdorelogio.pt"
baseurl:  #/ #/ para GHPages
google_analytics: 'UA-12132868-3'
disqus: ''
mailchimp-list: ''
include: ["_pages"]
permalink: /:title/
locale: pt_PT
google_site_verification: "S3a4VjTKbILICe59QOaVODVG8t2UdaOCBtXLQdcmWDg"


# Authors
authors:
  sal:
    name: Sal
    display_name: Sal
    avatar: 
    gravatar: 
    email: 
    web: 
    twitter: 
    description: "Author of Mediumish, a Bootstrap Medium styled template available for WordPress, HTML, Ghost and Jekyll. You are currently previewing Jekyll template demo."
  john:
    name: John
    display_name: John    
    avatar: 'assets/images/avatar.png'
    gravatar: 
    email: 
    web: 
    twitter: 
    description: "This is the author box. Write a short description of the author here. You are currently previewing Mediumish demo, a Jekyll template compatible with Github pages."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: ""
adsense-data-ad-slot: ""

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
